### ISSUE TITLE
UR Firmware V1.8 Incompatibilities

### ISSUE THREAD

**Issue by apether** [ros-industrial/universal_robot#16]
Hi, 

I recently tried to utilise this package on a UR5 Robot running V1.8.11281 of their software which was released on Aug 07 2013. The result was very similar to that described in issue 9, caused by changes between V1.6 and V1.7 so it appears this is similar. It also reported an unknown package type, so I guess more have been added.

https://github.com/ros-industrial/universal_robot/issues/9

Has anyone else tried running the package on a V1.8 robot? This was the first time I'd tried this package, I assume I would have had more luck on a robot running V1.7. 

Here is the console output:

```
linux@ubuntu:~$ roslaunch ur_bringup ur5.launch robot_ip:=192.168.0.102
... logging to /home/linux/.ros/log/4e12e310-2033-11e3-8faa-b888e3f3f398/roslaunch-ubuntu-3991.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://ubuntu:48369/

SUMMARY
========

PARAMETERS
 * /robot_description
 * /robot_ip_address
 * /rosdistro
 * /rosversion
 * /tf2_buffer_server/buffer_size

NODES
  /
    robot_state_publisher (robot_state_publisher/state_publisher)
    tf2_buffer_server (tf2_ros/buffer_server)
    ur_driver (ur_driver/driver.py)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[robot_state_publisher-1]: started with pid [4013]
process[ur_driver-2]: started with pid [4030]
process[tf2_buffer_server-3]: started with pid [4031]
Setting prefix to 
[WARN] [WallTime: 1379489595.494830] No calibration offset for joint "shoulder_pan_joint"
[WARN] [WallTime: 1379489595.496176] No calibration offset for joint "shoulder_lift_joint"
[WARN] [WallTime: 1379489595.497629] No calibration offset for joint "elbow_joint"
[WARN] [WallTime: 1379489595.499230] No calibration offset for joint "wrist_1_joint"
[WARN] [WallTime: 1379489595.501033] No calibration offset for joint "wrist_2_joint"
[WARN] [WallTime: 1379489595.503084] No calibration offset for joint "wrist_3_joint"
[ERROR] [WallTime: 1379489595.503234] Loaded calibration offsets: {}
Disconnected.  Reconnecting
[INFO] [WallTime: 1379489595.508918] Programming the robot
[INFO] [WallTime: 1379489595.511157] Programming the robot at 192.168.0.102
Exception in thread UR5Connection:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/linux/catkin_ws/src/universal_robot/ur_driver/driver.py", line 199, in __run
    self.__on_packet(packet)
  File "/home/linux/catkin_ws/src/universal_robot/ur_driver/driver.py", line 146, in __on_packet
    state = RobotState.unpack(buf)
  File "/home/linux/catkin_ws/src/universal_robot/ur_driver/deserialize.py", line 245, in unpack
    raise Exception("Unknown package type: %i" % ptype)
Exception: Unknown package type: 9

Handling a request
[2013-09-18 15:33:16.045235] Out: hello
[INFO] [WallTime: 1379489596.076069] Robot connected
The action server for this driver has been started
[2013-09-18 15:34:07.472608] on_goal
[2013-09-18 15:34:47.601144] Out: Braking
^C[tf2_buffer_server-3] killing on exit
[ur_driver-2] killing on exit
[robot_state_publisher-1] killing on exit
Traceback (most recent call last):
  File "/home/linux/catkin_ws/src/universal_robot/ur_driver/driver.py", line 697, in <module>
    if __name__ == '__main__': main()
  File "/home/linux/catkin_ws/src/universal_robot/ur_driver/driver.py", line 658, in main
    time.sleep(0.2)
KeyboardInterrupt
shutting down processing monitor...
... shutting down processing monitor complete
done

```

Here is a list of updates in V1.8, not sure which need to be added though:

```
URScript:

    Commands for Conveyor Tracking
        track_conveyor_linear(direction, ticksPerMeter) makes robot motions follow a linear conveyor
        track_conveyor_circular(center, ticksPerRevolution,rotate_tool) makes the robot motions follow a circular conveyor (round table)
        stop_conveyor_tracking() returns to normal robot control
        set_conveyor_tick_count(value) sends the value of an absolute encoder to the controller
        get_conveyor_tick_count() returns the estimated conveyor tick count, using interpolation
        conveyor_pulse_decode(type,A,B) makes controller decode pulses (edges or quadrature pulses with less than 50Hz frequency) as input to the conveyor tracker 
    Tutorials for conveyor tracking at http://support.universal-robots.com/Technical/ConveyorTracking
    Added string comparison operators ( ==,!=, <, >, <=, >=) e.g. to check whether a string is empty (eg. str == "")
    Added a "norm" operator for arrays "norm(myArray)"
    Arrays can no longer change length at runtime
    Script function textmsg() can now take two arguments, so you can write for instance a string and a variable to the log-tab
    Script functions get_target_tcp_pose(), get_actual_tcp_pose(), get_target_tcp_speed(), and get_actual_tcp_speed() now uses the specified tcp position in the calculations (Note! it may change behaviour of programs that use these script functions) 
```

Hope this is useful, I plan to try downgrading the robot to V1.7 to try it again. Please let me know if there's anything I can do to help.

Thanks,

Andy

**Comment by shaun-edwards** [comment]
@apether, thanks for the report.  I will reach out to universal to see if they can provide the required documentation to fix this problem.

**Comment by shaun-edwards** [comment]
I've received the information that is required to fix this latest issue.  This is not high on our list, since we are still at software version 1.6.  If anybody from the community is willing to patch this issue, I can share what I know.  

A better (longer term) fix may be to just parse out unknown packages (their length is included in the packet structure,  as the first 4 bytes).  

I've also updated the wiki to reflect the universal software version limitation: http://wiki.ros.org/universal_robot

**Comment by gavanderhoorn** [comment]
@shaun-edwards: we have a couple of UR5s here which can be updated. If you send me the documentation, I'll look into patching this.

**Comment by gavanderhoorn** [comment]
@shaun-edwards: ping?

**Comment by shaun-edwards** [comment]
I don't have all the documentation yet, but I thought we were going to just fix this by parsing the unknown packages.  Am I missing something?

**Comment by gavanderhoorn** [comment]
Right, a misunderstanding. I was under the impression we would be fixing the parser for the 1.8 protocol with the new information, and use ignore-unknown-packets for any future changes. I'll get on it then.

**Comment by apether** [comment]
I assume this has been updated now, tested on a v1.8 robot yesterday, worked well. Thanks!
